# Generated by Django 5.0.1 on 2024-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natid', models.IntegerField()),
                ('species', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(max_length=255)),
                ('altform', models.IntegerField()),
            ],
        ),
    ]
