# Generated by Django 5.0.1 on 2024-02-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeTracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
