# Generated by Django 5.0.1 on 2024-03-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeTracker', '0004_alter_pokemon_altform_alter_pokemon_type2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedcheckbox',
            name='checkbox_id',
            field=models.TextField(),
        ),
    ]
