# Generated by Django 5.0.1 on 2024-03-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeTracker', '0007_rename_checkedcheckbox_pokedexcheckedcheckbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shinydexcheckedcheckbox',
            name='checked_checkboxes',
            field=models.TextField(default='[]'),
        ),
    ]
